/* ===== #99 COURSE MAPPER ===== */
const _showView98=showView,_renderCourseDirectory98=renderCourseDirectory,_updateGpsDisplay98=updateGpsDisplay;
function mapperLocalCourse(){return localCourseDirectory.find(c=>c.id===activeCourseId)||localCourseDirectory.find(c=>courseKey(c.name)===courseKey(activeCourse()?.name||""))||null}
function ensureMapperHoles(c){if(!c)return null;if(!Array.isArray(c.holes)||c.holes.length!==18)c.holes=demoHoles.map((h,i)=>({hole:i+1,par:h.par,si:h.si,front:h.front,centre:h.centre,back:h.back,gps:{}}));else c.holes=c.holes.map((h,i)=>({...demoHoles[i],...h,hole:i+1,gps:h.gps||{}}));return c}
function persistMapperCourse(c){if(!c)return;let i=localCourseDirectory.findIndex(x=>x.id===c.id);if(i<0)i=localCourseDirectory.findIndex(x=>courseKey(x.name)===courseKey(c.name));if(i>=0)localCourseDirectory[i]=c;else localCourseDirectory.push(c);localStorage.setItem("drcCourseDirectory",JSON.stringify(localCourseDirectory))}
function mapperCount(c){if(!c||!Array.isArray(c.holes))return 0;let n=0;c.holes.forEach(h=>["front","centre","back"].forEach(k=>{if(h.gps&&validPoint(h.gps[k]))n++}));return n}
function setupMapperHoleSelect(){const s=$("mapperHole");if(!s||s.options.length===18)return;s.innerHTML="";for(let i=1;i<=18;i++){const o=document.createElement("option");o.value=i-1;o.textContent="Hole "+i;s.appendChild(o)}}
function renderMapper(){if(!$("mapperProgress"))return;setupMapperHoleSelect();const c=mapperLocalCourse()||activeCourse(),s=$("mapperHole"),idx=Math.max(0,Math.min(17,Number(s?.value||0))),acc=$("mapperAccuracy"),status=$("mapperStatus");if(acc)acc.textContent=gpsState.status==="LOCKED"&&Number.isFinite(gpsState.accuracy)?"±"+Math.round(gpsState.accuracy)+" m":"Waiting for GPS";const names={front:"Front",centre:"Centre",back:"Back"};if(!c){$("mapperProgress").textContent="0 / 54 points captured";$("mapperProgressFill").style.width="0%";["front","centre","back"].forEach(k=>{const b=$("capture"+k[0].toUpperCase()+k.slice(1));if(b){b.classList.remove("done");b.textContent=names[k].toUpperCase()}});if(status)status.innerHTML="<strong>Save or select a course first.</strong><br>Then map each green front, centre and back.";return}ensureMapperHoles(c);const count=mapperCount(c),h=c.holes[idx];$("mapperProgress").textContent=count+" / 54 points captured";$("mapperProgressFill").style.width=count/54*100+"%";["front","centre","back"].forEach(k=>{const b=$("capture"+k[0].toUpperCase()+k.slice(1)),done=h.gps&&validPoint(h.gps[k]);if(b){b.classList.toggle("done",!!done);b.textContent=(done?"✓ ":"")+names[k].toUpperCase()}});if(status){const rows=["front","centre","back"].map(k=>{const p=h.gps?.[k];return validPoint(p)?names[k]+": "+Number(p.lat).toFixed(6)+", "+Number(p.lon).toFixed(6)+" · ±"+Math.round(Number(p.accuracy)||0)+" m":names[k]+": —"});status.innerHTML="<strong>"+c.name+" · Hole "+(idx+1)+"</strong><br>"+rows.join("<br>")+(count===54?"<br><strong style='color:#35b96f'>GPS MAPPED · all 54 points complete.</strong>":"")}}
function saveCourse(){const name=$("courseName").value.trim();if(!name){alert("Enter the course name first.");return}const id="local-"+courseKey(name),old=localCourseDirectory.find(x=>courseKey(x.name)===courseKey(name));const c={id,name,teeType:$("teeType").value,teeColour:$("teeColour").value,aliases:old?.aliases||[],holes:old?.holes||null};const i=localCourseDirectory.findIndex(x=>courseKey(x.name)===courseKey(name));if(i>=0)localCourseDirectory[i]=c;else localCourseDirectory.push(c);localStorage.setItem("drcCourseDirectory",JSON.stringify(localCourseDirectory));localStorage.setItem("drcCourseSetup",JSON.stringify({name:c.name,teeType:c.teeType,teeColour:c.teeColour}));activeCourseId=c.id;localStorage.setItem("drcActiveCourseId",activeCourseId);renderCourseDirectory();renderMapper();alert("Course saved to directory.")}
function captureMapPoint(point){let c=mapperLocalCourse();if(!c){const a=activeCourse();if(a&&VERIFIED_COURSES.includes(a)){alert("Installed verified courses are protected. Save a local course to map it.");return}alert("Save or select a course first.");return}if(!("geolocation"in navigator)){alert("GPS is not available on this device.");return}ensureMapperHoles(c);const idx=Number($("mapperHole").value||0),existing=c.holes[idx].gps?.[point],label=point==="centre"?"CENTRE":point.toUpperCase();if(validPoint(existing)&&!confirm("Hole "+(idx+1)+" "+label+" is already saved. Replace it?"))return;$("mapperStatus").innerHTML="<strong>Capturing "+label+"...</strong><br>Hold still while DRC gets a fresh high-accuracy GPS fix.";navigator.geolocation.getCurrentPosition(pos=>{const accuracy=Number(pos.coords.accuracy);if(Number.isFinite(accuracy)&&accuracy>15&&!confirm("GPS accuracy is ±"+Math.round(accuracy)+" m. Save this point anyway?")){gpsSuccess(pos);renderMapper();return}const p={lat:Number(pos.coords.latitude),lon:Number(pos.coords.longitude),accuracy,capturedAt:new Date().toISOString()};if(!validPoint(p)){alert("DRC could not get a valid GPS point.");renderMapper();return}c.holes[idx].gps[point]=p;persistMapperCourse(c);holes=c.holes.map((h,i)=>({hole:i+1,par:Number(h.par)||demoHoles[i].par,si:Number(h.si)||demoHoles[i].si,front:Number(h.front)||demoHoles[i].front,centre:Number(h.centre)||demoHoles[i].centre,back:Number(h.back)||demoHoles[i].back,gps:h.gps||null}));gpsSuccess(pos);_renderCourseDirectory98();renderMapper();renderHole();const count=mapperCount(c);if(count===54)alert("Course mapping complete — all 54 GPS points are saved.")},e=>{gpsError(e);alert(e&&e.code===1?"Location permission is blocked.":"Could not get a fresh GPS fix. Try again.");renderMapper()},{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
showView=function(n){_showView98(n);if(n==="course")renderMapper()};
renderCourseDirectory=function(){_renderCourseDirectory98();renderMapper()};
updateGpsDisplay=function(){_updateGpsDisplay98();renderMapper()};

/* ===== #100 MAPPER COMPLETE + REAL SATELLITE ===== */
let mappingHole=Math.max(0,Math.min(17,Number(localStorage.getItem("drcMappingHole")||0))),satelliteMap=null,satellitePlayer=null,satelliteGreenLayer=null,mapMode=localStorage.getItem("drcMapMode")||"gps";
function mappedPointCount(c){return mapperCount(c)}
function setMappingHole(v){mappingHole=Math.max(0,Math.min(17,Number(v)||0));localStorage.setItem("drcMappingHole",String(mappingHole));if($("mapperHole"))$("mapperHole").value=String(mappingHole);renderMapper()}
function previousMapperHole(){setMappingHole(Math.max(0,mappingHole-1))}
function nextMapperHole(){setMappingHole(Math.min(17,mappingHole+1))}
function setupMapperHoleSelect(){const s=$("mapperHole");if(!s)return;if(s.options.length!==18){s.innerHTML="";for(let i=1;i<=18;i++){const o=document.createElement("option");o.value=i-1;o.textContent="Hole "+i;s.appendChild(o)}}s.value=String(mappingHole)}
function renderCourseDirectory(){const s=$("courseDirectorySelect");if(!s)return;const current=s.value;s.innerHTML='<option value="">— Select course —</option>';getCourseDirectory().forEach(c=>{const o=document.createElement("option"),n=mappedPointCount(c),tag=courseHasGps(c)?" • GPS":n?" • MAP "+n+"/54":" • SAVED";o.value=c.id;o.textContent=c.name+tag;s.appendChild(o)});if(activeCourseId)s.value=activeCourseId;else if(current)s.value=current;updateCourseDirectoryStatus();renderMapper()}
function updateCourseDirectoryStatus(){const e=$("courseDirectoryStatus"),c=activeCourse();if(!e)return;if(!c){e.className="gps-coordinates directory-warn";e.innerHTML="No mapped GPS course loaded.<br>Round distances are currently demo/static.";return}const n=mappedPointCount(c);if(courseHasGps(c)){e.className="gps-coordinates directory-good";e.innerHTML="<strong>"+c.name+"</strong><br>GPS MAPPED — 54 / 54 points.<br>Front / centre / back now use live phone position."}else{e.className="gps-coordinates directory-warn";e.innerHTML="<strong>"+c.name+"</strong><br>Mapping "+n+" / 54 points.<br>Round distances remain demo/static until mapping is complete."}}
function renderMapper(){if(!$("mapperProgress"))return;setupMapperHoleSelect();const c=mapperLocalCourse(),idx=mappingHole,acc=$("mapperAccuracy"),status=$("mapperStatus"),names={front:"Front",centre:"Centre",back:"Back"};if(acc)acc.textContent=gpsState.status==="LOCKED"&&Number.isFinite(gpsState.accuracy)?"±"+Math.round(gpsState.accuracy)+" m":"Waiting for GPS";if(!c){$("mapperProgress").textContent="0 / 54 points captured";$("mapperProgressFill").style.width="0%";["front","centre","back"].forEach(k=>{const b=$("capture"+k[0].toUpperCase()+k.slice(1));if(b){b.classList.remove("done");b.textContent=names[k].toUpperCase()}});if(status)status.innerHTML="<strong>Save or select a local course first.</strong><br>Then map each green front, centre and back.";return}ensureMapperHoles(c);const count=mappedPointCount(c),h=c.holes[idx];$("mapperProgress").textContent=count+" / 54 points captured";$("mapperProgressFill").style.width=count/54*100+"%";["front","centre","back"].forEach(k=>{const b=$("capture"+k[0].toUpperCase()+k.slice(1)),done=h.gps&&validPoint(h.gps[k]);if(b){b.classList.toggle("done",!!done);b.textContent=(done?"✓ ":"")+names[k].toUpperCase()}});if(status){const rows=["front","centre","back"].map(k=>{const p=h.gps?.[k];return validPoint(p)?names[k]+": "+Number(p.lat).toFixed(6)+", "+Number(p.lon).toFixed(6)+" · ±"+Math.round(Number(p.accuracy)||0)+" m":names[k]+": —"});status.innerHTML="<strong>"+c.name+" · Hole "+(idx+1)+"</strong><br>"+rows.join("<br>")+(count===54?"<br><strong style='color:#35b96f'>GPS MAPPED · all 54 points complete.</strong>":"")}}
function captureMapPoint(point){let c=mapperLocalCourse();if(!c){alert("Save or select a local course first.");return}if(!("geolocation" in navigator)){alert("GPS is not available on this device.");return}ensureMapperHoles(c);const idx=mappingHole,existing=c.holes[idx].gps?.[point],label=point==="centre"?"CENTRE":point.toUpperCase();if(validPoint(existing)&&!confirm("Hole "+(idx+1)+" "+label+" is already saved. Replace it?"))return;$("mapperStatus").innerHTML="<strong>Capturing "+label+"...</strong><br>Hold still while DRC gets a fresh high-accuracy GPS fix.";navigator.geolocation.getCurrentPosition(p=>{const accuracy=Number(p.coords.accuracy);if(Number.isFinite(accuracy)&&accuracy>15&&!confirm("GPS accuracy is ±"+Math.round(accuracy)+" m. Save this point anyway?")){gpsSuccess(p);renderMapper();return}const pointData={lat:Number(p.coords.latitude),lon:Number(p.coords.longitude),accuracy:Number(p.coords.accuracy),timestamp:p.timestamp||Date.now()};if(!validPoint(pointData)){alert("DRC could not get a valid GPS point.");renderMapper();return}c.holes[idx].gps[point]=pointData;persistMapperCourse(c);holes=c.holes.map((h,i)=>({hole:i+1,par:Number(h.par)||demoHoles[i].par,si:Number(h.si)||demoHoles[i].si,front:Number(h.front)||demoHoles[i].front,centre:Number(h.centre)||demoHoles[i].centre,back:Number(h.back)||demoHoles[i].back,gps:h.gps||null}));gpsSuccess(p);renderCourseDirectory();renderHole();refreshSatelliteOverlay();const complete=["front","centre","back"].every(k=>validPoint(c.holes[idx].gps[k]));if(point==="back"&&complete&&idx<17)setMappingHole(idx+1);if(mappedPointCount(c)===54)alert("Course mapping complete — all 54 GPS points are saved.")},e=>{gpsError(e);alert(e&&e.code===1?"Location permission is blocked.":"Could not get a fresh GPS fix. Try again.");renderMapper()},{enableHighAccuracy:true,maximumAge:0,timeout:15000})}
function clearMappedHole(){const c=mapperLocalCourse();if(!c){alert("Save or select a local course first.");return}ensureMapperHoles(c);if(!confirm("Clear all FRONT, CENTRE and BACK GPS points for Hole "+(mappingHole+1)+"?"))return;c.holes[mappingHole].gps={};persistMapperCourse(c);renderCourseDirectory();renderMapper();refreshSatelliteOverlay()}
function resetCourseMap(){const c=mapperLocalCourse();if(!c){alert("Save or select a local course first.");return}if(!confirm("Reset ALL 54 GPS mapping points for "+c.name+"?"))return;ensureMapperHoles(c);c.holes.forEach(h=>h.gps={});persistMapperCourse(c);setMappingHole(0);renderCourseDirectory();renderHole();refreshSatelliteOverlay()}
function initSatelliteMap(){if(satelliteMap||!window.L||!$("satelliteMap"))return!!satelliteMap;satelliteMap=L.map("satelliteMap",{zoomControl:false,attributionControl:true});L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{maxZoom:20,attribution:"Tiles © Esri"}).addTo(satelliteMap);satelliteGreenLayer=L.layerGroup().addTo(satelliteMap);return true}
function refreshSatelliteOverlay(){if(mapMode!=="aerial"||!initSatelliteMap())return;if(Number.isFinite(gpsState.latitude)&&Number.isFinite(gpsState.longitude)){const ll=[gpsState.latitude,gpsState.longitude];if(!satellitePlayer)satellitePlayer=L.circleMarker(ll,{radius:7,weight:3,color:"#fff",fillColor:"#1678ff",fillOpacity:1}).addTo(satelliteMap);else satellitePlayer.setLatLng(ll);satelliteMap.setView(ll,18)}if(satelliteGreenLayer){satelliteGreenLayer.clearLayers();const c=activeCourse(),h=c?.holes?.[currentHole];if(h?.gps)["front","centre","back"].forEach((k,i)=>{const p=h.gps[k];if(validPoint(p))L.circleMarker([Number(p.lat),Number(p.lon)],{radius:6,weight:2,color:"#fff",fillColor:i===0?"#35b96f":i===1?"#e4b83d":"#d94a4a",fillOpacity:1}).bindTooltip(k.toUpperCase()).addTo(satelliteGreenLayer)})}}
function toggleMapMode(mode){mapMode=mode==="aerial"?"aerial":"gps";localStorage.setItem("drcMapMode",mapMode);const card=document.querySelector(".map-card");if(card)card.classList.toggle("aerial",mapMode==="aerial");$("gpsMapBtn")?.classList.toggle("active",mapMode==="gps");$("aerialMapBtn")?.classList.toggle("active",mapMode==="aerial");if(mapMode==="aerial"){if(!initSatelliteMap()){alert("Satellite map could not load. Check internet connection.");return toggleMapMode("gps")}setTimeout(()=>{satelliteMap.invalidateSize();refreshSatelliteOverlay()},80)}}
const _gpsSuccess100=gpsSuccess;gpsSuccess=function(p){_gpsSuccess100(p);refreshSatelliteOverlay()};
const _renderHole100=renderHole;renderHole=function(){_renderHole100();refreshSatelliteOverlay()};
const _loadDirectoryCourse100=loadDirectoryCourse;loadDirectoryCourse=function(id){_loadDirectoryCourse100(id);renderMapper();refreshSatelliteOverlay()};
const _saveCourse100=saveCourse;saveCourse=function(){_saveCourse100();renderMapper()};
loadSettings();renderBag();renderWarmup();renderRoutine();renderHole();setupRecognition();startGps();toggleMapMode(mapMode);
