const $=id=>document.getElementById(id),$$=s=>document.querySelectorAll(s),YARDS_TO_METRES=.9144;
let currentHole=Number(localStorage.getItem("drcCurrentHole")||0),recognition=null,listening=false,gpsWatchId=null,unitMode=localStorage.getItem("drcUnitMode")||"metric",activeCourseId=localStorage.getItem("drcActiveCourseId")||"";
const currentConditions={temperatureC:24,windSpeedKmh:8,windDirection:"none"},gpsState={status:"SEARCHING",latitude:null,longitude:null,accuracy:null,altitude:null,heading:null,speed:null,timestamp:null};
const demoHoles=[{hole:1,par:5,si:5,front:480,centre:498,back:512},{hole:2,par:4,si:11,front:356,centre:369,back:382},{hole:3,par:3,si:15,front:142,centre:151,back:160},{hole:4,par:4,si:1,front:396,centre:410,back:423},{hole:5,par:5,si:7,front:475,centre:491,back:506},{hole:6,par:3,si:17,front:128,centre:139,back:150},{hole:7,par:4,si:9,front:348,centre:361,back:374},{hole:8,par:4,si:3,front:382,centre:397,back:410},{hole:9,par:4,si:13,front:335,centre:349,back:362},{hole:10,par:4,si:6,front:368,centre:381,back:394},{hole:11,par:5,si:4,front:492,centre:508,back:523},{hole:12,par:3,si:16,front:151,centre:162,back:173},{hole:13,par:4,si:10,front:346,centre:360,back:373},{hole:14,par:4,si:2,front:401,centre:416,back:429},{hole:15,par:5,si:8,front:485,centre:501,back:517},{hole:16,par:3,si:18,front:121,centre:132,back:143},{hole:17,par:4,si:12,front:355,centre:369,back:382},{hole:18,par:4,si:14,front:361,centre:375,back:389}];
let holes=demoHoles.map(h=>({...h})),localCourseDirectory=JSON.parse(localStorage.getItem("drcCourseDirectory")||"[]");
const VERIFIED_COURSES=[];
function courseKey(s){return String(s||"").toLowerCase().replace(/[^a-z0-9]/g,"")}
function getCourseDirectory(){const all=[...VERIFIED_COURSES,...localCourseDirectory],seen=new Set(),out=[];all.forEach(c=>{const k=courseKey(c.name);if(k&&!seen.has(k)){seen.add(k);out.push(c)}});return out}
function activeCourse(){return getCourseDirectory().find(c=>c.id===activeCourseId)||null}
function validPoint(p){return p&&Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lon))}
function courseHasGps(c){return!!(c&&Array.isArray(c.holes)&&c.holes.length===18&&c.holes.every(h=>h.gps&&validPoint(h.gps.front)&&validPoint(h.gps.centre)&&validPoint(h.gps.back)))}
function distanceMetres(a,b,c,d){const R=6371000,r=Math.PI/180,x=(c-a)*r,y=(d-b)*r,z=Math.sin(x/2)**2+Math.cos(a*r)*Math.cos(c*r)*Math.sin(y/2)**2;return 2*R*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}
function getLiveHoleDistances(){const c=activeCourse();if(gpsState.status!=="LOCKED"||!courseHasGps(c))return null;const h=c.holes[currentHole];return{front:distanceMetres(gpsState.latitude,gpsState.longitude,+h.gps.front.lat,+h.gps.front.lon),centre:distanceMetres(gpsState.latitude,gpsState.longitude,+h.gps.centre.lat,+h.gps.centre.lon),back:distanceMetres(gpsState.latitude,gpsState.longitude,+h.gps.back.lat,+h.gps.back.lon),live:true}}
function getDisplayHoleDistances(){const h=holes[currentHole];return getLiveHoleDistances()||{front:h.front,centre:h.centre,back:h.back,live:false}}
function getCurrentCentreDistance(){return getDisplayHoleDistances().centre}
function renderCourseDirectory(){const s=$("courseDirectorySelect");if(!s)return;const cur=s.value;s.innerHTML='<option value="">— Select course —</option>';getCourseDirectory().forEach(c=>{const o=document.createElement("option");o.value=c.id;o.textContent=c.name+(courseHasGps(c)?" • GPS":" • SAVED");s.appendChild(o)});if(activeCourseId)s.value=activeCourseId;else if(cur)s.value=cur;updateCourseDirectoryStatus()}
function updateCourseDirectoryStatus(){const e=$("courseDirectoryStatus"),c=activeCourse();if(!e)return;if(!c){e.className="gps-coordinates directory-warn";e.innerHTML="No mapped GPS course loaded.<br>Round distances are currently demo/static.";return}e.className="gps-coordinates "+(courseHasGps(c)?"directory-good":"directory-warn");e.innerHTML="<strong>"+c.name+"</strong><br>"+(courseHasGps(c)?"GPS MAPPED — 54 / 54 points.":"GPS mapping not complete yet.")}
function updateGpsDisplay(){const b=$("gpsBadge"),s=$("gpsStatusText"),c=$("gpsCoordinates");if(s)s.textContent=gpsState.status;if(b){b.classList.remove("lock","error");if(gpsState.status==="LOCKED"){b.textContent="GPS ±"+Math.round(gpsState.accuracy)+" m";b.classList.add("lock")}else{b.textContent="GPS "+gpsState.status;if(["BLOCKED","UNAVAILABLE","ERROR"].includes(gpsState.status))b.classList.add("error")}}if(c)c.innerHTML=Number.isFinite(gpsState.latitude)?"Latitude: "+gpsState.latitude.toFixed(6)+"<br>Longitude: "+gpsState.longitude.toFixed(6)+"<br>Accuracy: ±"+Math.round(gpsState.accuracy)+" m":"Latitude: —<br>Longitude: —<br>Accuracy: —"}
function gpsSuccess(p){if(!p||!p.coords)return;gpsState.status="LOCKED";gpsState.latitude=+p.coords.latitude;gpsState.longitude=+p.coords.longitude;gpsState.accuracy=+p.coords.accuracy;gpsState.timestamp=p.timestamp||Date.now();updateGpsDisplay()}
function gpsError(e){gpsState.status=!e?"ERROR":e.code===1?"BLOCKED":e.code===2?"UNAVAILABLE":e.code===3?"SEARCHING":"ERROR";updateGpsDisplay()}
function startGps(){if(!("geolocation"in navigator)){gpsState.status="UNAVAILABLE";return updateGpsDisplay()}gpsState.status="SEARCHING";updateGpsDisplay();navigator.geolocation.getCurrentPosition(gpsSuccess,gpsError,{enableHighAccuracy:true,timeout:15000,maximumAge:0});if(gpsWatchId===null)gpsWatchId=navigator.geolocation.watchPosition(gpsSuccess,gpsError,{enableHighAccuracy:true,timeout:20000,maximumAge:3000})}
function refreshGps(){gpsState.status="SEARCHING";updateGpsDisplay();navigator.geolocation.getCurrentPosition(gpsSuccess,gpsError,{enableHighAccuracy:true,timeout:15000,maximumAge:0})}
