let bagMetres=JSON.parse(localStorage.getItem("drcBagMetres")||"null")||{"Driver":230,"3 Wood":210,"5 Wood":195,"4 Iron":180,"5 Iron":170,"6 Iron":160,"7 Iron":150,"8 Iron":140,"9 Iron":130,"PW":115,"GW":100,"SW":85,"LW":70},holeScores=JSON.parse(localStorage.getItem("drcHoleScores")||"{}"),practiceType="Wedges",practiceShape="STRAIGHT",practiceCounts={good:0,left:0,right:0,short:0,long:0};
const warmupSteps=[["Loosen Up","Easy movement and mobility"],["Short Wedges","Build rhythm with short wedges"],["Mid Irons","Controlled mid-iron strikes"],["Long Club","A few longer clubs"],["Driver","Finish full swings with driver"],["Chipping","Check strike and landing spot"],["Putting","Speed first, then start line"],["Ready","One committed final shot"]],routineSteps=[["Target","Choose the exact target"],["Lie","Read the lie before choosing the shot"],["Club","Choose the club for the shot required"],["Picture","See the ball flight and landing point"],["Commit","Commit fully to the decision"],["Breathe","One calm breath"],["Reset","Step in and execute"],["Next","Accept the result and move on"]];
let warmupState=JSON.parse(localStorage.getItem("drcWarmupState")||"null")||new Array(8).fill(false),routineState=JSON.parse(localStorage.getItem("drcRoutineState")||"null")||new Array(8).fill(false);
function displayDistance(m){return unitMode==="imperial"?{value:Math.round(m/YARDS_TO_METRES),unit:"yds"}:{value:Math.round(m),unit:"m"}}
function formatDistance(m){const d=displayDistance(m);return d.value+" "+d.unit}
function hideAllViews(){$$(".view").forEach(v=>v.classList.remove("active"))}
function clearBottomNav(){$$(".bottom-nav button").forEach(b=>b.classList.remove("active"))}
function showView(n){hideAllViews();clearBottomNav();$(n+"View").classList.add("active");const nav={round:"navRound",caddie:"navCaddie",bag:"navBag",course:"navCourse",more:"navMore"};if(nav[n])$(nav[n]).classList.add("active");if(n==="caddie")updateCaddiePage();if(n==="bag")renderBag();if(n==="course"){updateCoursePage();renderCourseDirectory();renderMapper()}if(n==="more")updateMorePage();if(n==="round"&&typeof updateSatellite==="function")updateSatellite()}
function openTool(n){hideAllViews();clearBottomNav();$(n+"View").classList.add("active");$("navMore").classList.add("active");if(n==="scorecard")renderScorecard();if(n==="practice")renderPractice();if(n==="warmup")renderWarmup();if(n==="routines")renderRoutine()}
function applyMapLayout(){const m=holeMaps[currentHole],f=$("fairway"),g=$("green"),b=$("bunker"),w=$("water"),fl=$("flag"),l=$("shotLine");f.style.inset=m[1];f.style.clipPath=m[0];[g.style.top,g.style.left,g.style.width,g.style.height]=m[2];[b.style.top,b.style.left,b.style.width,b.style.height]=m[3];b.style.transform="rotate("+m[3][4]+")";[w.style.top,w.style.right,w.style.bottom,w.style.left,w.style.width,w.style.height]=m[4];[fl.style.top,fl.style.left]=m[5];[l.style.top,l.style.bottom,l.style.left]=m[6]}
function renderConditions(){$("weatherTemp").textContent=Math.round(currentConditions.temperatureC)+"°C";$("weatherWind").textContent="Wind "+Math.round(currentConditions.windSpeedKmh)+" km/h"}
function renderDistancePanel(){const d=getDisplayHoleDistances(),f=displayDistance(d.front),c=displayDistance(d.centre),b=displayDistance(d.back);$("frontDistance").textContent=f.value;$("centreDistance").textContent=c.value;$("centreBig").textContent=c.value;$("backDistance").textContent=b.value;$("mapFullDistance").textContent=c.value;$("mapMidDistance").textContent=Math.round(c.value*.56);$("mapNearDistance").textContent=Math.round(c.value*.46);$$(".unit").forEach(e=>e.textContent=c.unit)}
function renderHole(){const h=holes[currentHole];$("holeNumber").textContent=h.hole;$("holePar").textContent=h.par;$("holeSI").textContent=h.si;renderDistancePanel();applyMapLayout();loadHoleScore();recommendClub();localStorage.setItem("drcCurrentHole",currentHole);updateCaddiePage();updateCoursePage();updateCourseDirectoryStatus();if(typeof updateSatellite==="function")updateSatellite()}
function nextHole(){if(currentHole<17)currentHole++;renderHole()}
function previousHole(){if(currentHole>0)currentHole--;renderHole()}
function getScoreData(){const n=holes[currentHole].hole;if(!holeScores[n])holeScores[n]={score:0,putts:0,gir:false,fairway:false,penalty:0};return holeScores[n]}
function saveScores(){localStorage.setItem("drcHoleScores",JSON.stringify(holeScores))}
function loadHoleScore(){const d=getScoreData();$("scoreValue").textContent=d.score;$("puttsValue").textContent=d.putts;$("penaltyValue").textContent=d.penalty;$("girButton").classList.toggle("active",d.gir);$("fairwayButton").classList.toggle("active",d.fairway)}
function changeScore(n){const d=getScoreData();d.score=Math.max(0,d.score+n);saveScores();loadHoleScore()}
function changePutts(n){const d=getScoreData();d.putts=Math.max(0,d.putts+n);saveScores();loadHoleScore()}
function changePenalty(n){const d=getScoreData();d.penalty=Math.max(0,d.penalty+n);saveScores();loadHoleScore()}
function toggleGir(){const d=getScoreData();d.gir=!d.gir;saveScores();loadHoleScore()}
function toggleFairway(){const d=getScoreData();d.fairway=!d.fairway;saveScores();loadHoleScore()}
function chooseNearestClub(t){let s="Driver",x=Infinity;Object.entries(bagMetres).forEach(([c,v])=>{const d=Math.abs(t-Number(v));if(d<x){x=d;s=c}});return s}
function getClubOrderedList(){return Object.entries(bagMetres).map(([club,carry])=>({club,carry:Number(carry)})).sort((a,b)=>b.carry-a.carry)}
function getClubAboveDistance(t){const c=getClubOrderedList();let b=c[c.length-1];for(const i of c)if(i.carry>=t)b=i;return b.club}
function chooseClubForShot(t,l,h){let c=chooseNearestClub(t);if(t>Math.max(...Object.values(bagMetres).map(Number)))return"Driver";if(l==="greenside bunker"&&t<=45){if(bagMetres.SW)return"SW";if(bagMetres.LW)return"LW"}if(l==="deep rough"&&t>145){const a=getClubOrderedList(),i=a.findIndex(x=>x.club===c),s=a[i+1];if(i>=0&&s&&s.club!=="Driver")c=s.club}if(h.short&&l!=="deep rough"&&l!=="greenside bunker")c=getClubAboveDistance(t);return c}
function recommendClub(){const t=getCurrentCentreDistance(),l=Math.max(...Object.values(bagMetres).map(Number));setRecommendedClub(t>l?"Driver":chooseNearestClub(t))}
function setRecommendedClub(c){if(bagMetres[c]===undefined)return;$("recommendedClub").textContent=c;const d=displayDistance(bagMetres[c]);$("recommendedCarry").textContent=d.value+" "+d.unit;$("clubSelect").value=c;updateCaddiePage()}
function manualClubChange(){setRecommendedClub($("clubSelect").value)}
function getCaddieName(){return $("caddieName").value.trim()||"Pete"}
function saveCaddieName(){const n=getCaddieName();$("caddieName").value=n;$("askName").textContent=n;$("largeCaddieName").textContent=n;$("moreCaddieName").value=n;localStorage.setItem("drcCaddieName",n);setCaddieAnswers("Ready. Ask "+n+" for the shot.")}
function saveCaddieNameFromMore(){$("caddieName").value=$("moreCaddieName").value.trim()||"Pete";saveCaddieName()}
function setListeningState(on){listening=on;["micButton","largeMic"].forEach(id=>{if($(id))$(id).classList.toggle("listening",on)})}
function setCaddieAnswers(t){if($("caddieAnswer"))$("caddieAnswer").textContent=t;if($("largeCaddieAnswer"))$("largeCaddieAnswer").textContent=t}
function setupRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){recognition=null;return false}try{recognition=new SR();recognition.lang="en-AU";recognition.continuous=false;recognition.interimResults=false;recognition.maxAlternatives=3;recognition.onstart=()=>{setListeningState(true);setCaddieAnswers("Listening...")};recognition.onresult=e=>{if(!e.results||!e.results.length)return;const t=e.results[0][0]?.transcript?.trim()||"";t?handleGolfCommand(t):setCaddieAnswers("Didn't catch that. Tap the mic and try again.")};recognition.onerror=e=>{let m="Didn't catch that clearly. Tap the mic and try again.";if(e.error==="not-allowed"||e.error==="service-not-allowed")m="Microphone permission is blocked.";else if(e.error==="no-speech")m="Didn't hear anything. Tap the mic and speak again.";else if(e.error==="audio-capture")m="The microphone isn't available right now.";else if(e.error==="network")m="Voice recognition couldn't reach the speech service.";setCaddieAnswers(m)};recognition.onend=()=>setListeningState(false);return true}catch(e){recognition=null;return false}}
function askCaddie(){if(listening&&recognition){try{recognition.stop()}catch(e){}return}if(!recognition&&!setupRecognition()){setCaddieAnswers("Voice recognition is not available on this device.");return}try{recognition.start()}catch(e){recognition=null;if(setupRecognition())try{recognition.start()}catch(x){setCaddieAnswers("The microphone couldn't start. Tap it again.")}}}
function normaliseSpeech(t){return String(t||"").toLowerCase().trim().replace(/[.,!?]/g," ").replace(/\bruff\b|\broughh\b/g,"rough").replace(/\bfare way\b|\bfair way\b/g,"fairway").replace(/\bhead win\b/g,"headwind").replace(/\btail win\b/g,"tailwind").replace(/\bcross win\b/g,"crosswind").replace(/(\d+(?:\.\d+)?)\s*(?:km|kph|kmh|kilometres?|kilometers?)\s+when\b/g,"$1 km wind").replace(/(\d+(?:\.\d+)?)\s+when\b/g,"$1 wind").replace(/\bwind into\b|\binto wind\b/g,"headwind").replace(/\bwind behind\b|\bhelping wind\b/g,"tailwind").replace(/\s+/g," ").trim()}
function extractNumbers(t){const m=t.match(/\d+(?:\.\d+)?/g);return m?m.map(Number):[]}
function parseDistance(t){let m=t.match(/(\d+(?:\.\d+)?)\s*(?:metres?|meters?|meter|metre|m)\b/);if(m)return{value:Number(m[1]),explicit:true};m=t.match(/(\d+(?:\.\d+)?)\s*(?:yards?|yard|yds?|yd)\b/);if(m)return{value:Number(m[1])*YARDS_TO_METRES,explicit:true};const n=extractNumbers(t)[0];if(n>=20&&n<=700)return{value:unitMode==="imperial"?n*YARDS_TO_METRES:n,explicit:false};return null}
function parseLie(t){if(/\bdeep rough\b|\bheavy rough\b|\bthick rough\b|\bbad rough\b|\blong rough\b/.test(t))return"deep rough";if(/\blight rough\b|\bfirst cut\b|\bsemi rough\b/.test(t))return"light rough";if(/\brough\b/.test(t))return"rough";if(/\bfairway bunker\b|\bpot bunker\b/.test(t))return"fairway bunker";if(/\bgreenside bunker\b|\bgreen side bunker\b/.test(t))return"greenside bunker";if(/\bbunker\b|\bsand\b/.test(t))return"bunker";if(/\btee\b|\btee box\b/.test(t))return"tee";return"fairway"}
function parseLieQuality(t){if(/\bsitting up\b|\bgood lie\b|\bclean lie\b|\bfluffy\b/.test(t))return"good";if(/\bsitting down\b|\bburied\b|\bplugged\b|\bbad lie\b|\bdeep lie\b/.test(t))return"bad";return"normal"}
function parseWind(t){const r={speed:Number(currentConditions.windSpeedKmh)||0,direction:currentConditions.windDirection||"none"};let m=t.match(/(\d+(?:\.\d+)?)\s*(?:km\/?h|kmh|kph|kilometres? per hour|kilometers? per hour|km)\b/);if(m)r.speed=Number(m[1]);else{m=t.match(/(\d+(?:\.\d+)?)\s*(?:mph|miles? per hour)\b/);if(m)r.speed=Number(m[1])*1.60934;else{m=t.match(/(\d+(?:\.\d+)?)\s+wind\b/);if(m&&Number(m[1])<=80)r.speed=Number(m[1])}}if(/\bheadwind\b|\bhead wind\b|\binto the wind\b|\bwind against\b/.test(t))r.direction="head";else if(/\btailwind\b|\btail wind\b|\bdownwind\b|\bwind behind\b/.test(t))r.direction="tail";else if(/\bleft to right\b|\bleft-to-right\b/.test(t))r.direction="ltr";else if(/\bright to left\b|\bright-to-left\b/.test(t))r.direction="rtl";else if(/\bcrosswind\b|\bcross wind\b/.test(t))r.direction="cross";return r}
function parseElevation(t){let m=t.match(/(\d+(?:\.\d+)?)\s*(?:metres?|meters?|m)?\s*(?:uphill|up hill)\b/);if(m)return Number(m[1]);m=t.match(/(\d+(?:\.\d+)?)\s*(?:metres?|meters?|m)?\s*(?:downhill|down hill)\b/);if(m)return-Number(m[1]);if(/\buphill\b|\bup hill\b/.test(t))return 5;if(/\bdownhill\b|\bdown hill\b/.test(t))return-5;return 0}
function parseHazards(t){return{water:/\bwater\b|\bpond\b|\blake\b|\bcreek\b|\bhazard\b/.test(t),bunker:/\bbunker\b|\bsand\b/.test(t),trees:/\btrees?\b/.test(t),trouble:/\btrouble\b|\bob\b|\bout of bounds\b/.test(t),left:/\bleft\b/.test(t),right:/\bright\b/.test(t),short:/\bshort\b|\bfront\b/.test(t),long:/\blong\b|\bback\b/.test(t)}}
function calculatePlayingDistance(base,lie,q,wind,elevation){let p=base;if(lie==="light rough")p*=1.015;else if(lie==="rough")p*=1.04;else if(lie==="deep rough")p*=1.07;else if(lie==="fairway bunker")p*=1.045;if(q==="bad"&&(lie==="rough"||lie==="deep rough"))p*=1.025;if(q==="good"&&(lie==="rough"||lie==="light rough"))p-=base*.01;const w=(wind.speed/1.60934)*.75*YARDS_TO_METRES;if(wind.direction==="head")p+=w;if(wind.direction==="tail")p-=w;if(elevation>0)p+=base*.05;if(elevation<0)p-=base*.05;return Math.max(1,p)}
function describeLie(l,q){if(l==="deep rough")return q==="bad"?"deep rough, sitting down":"deep rough";if(l==="rough")return q==="good"?"rough, sitting up":q==="bad"?"rough, sitting down":"rough";return l}
function buildHazardAdvice(h){if(h.water){if(h.left)return"Water left — favour right-centre.";if(h.right)return"Water right — favour left-centre.";if(h.short)return"Water short — cover it.";if(h.long)return"Water long — centre is enough.";return"Water in play — safe side."}if(h.bunker){if(h.left)return"Bunker left — favour right.";if(h.right)return"Bunker right — favour left.";if(h.short)return"Bunker short — cover it.";if(h.long)return"Bunker long — centre is enough.";return"Bunker in play."}if(h.trees)return h.left?"Trees left — favour right.":h.right?"Trees right — favour left.":"Take the clear window.";if(h.trouble)return h.left?"Trouble left — favour right.":h.right?"Trouble right — favour left.":"Keep the big miss out.";return""}
function buildWindAdvice(w){const s=w.speed?Math.round(w.speed)+" km/h ":"";if(w.direction==="head")return s+"headwind — flight it down.";if(w.direction==="tail")return s+"tailwind — allow extra carry.";if(w.direction==="ltr")return s+"left-to-right — start left.";if(w.direction==="rtl")return s+"right-to-left — start right.";if(w.direction==="cross")return s+"crosswind — allow for it.";return w.speed?s+"wind.":""}
function buildLieCue(l,q){if(l==="deep rough")return"Get it out cleanly.";if(l==="rough"&&q==="good")return"Flyer possible.";if(l==="rough"&&q==="bad")return"Clean contact first.";if(l==="fairway bunker")return"Clean strike.";if(l==="greenside bunker")return"Use the bounce.";if(l==="bunker")return"Check the lip.";return""}
function handleGolfCommand(command){const original=command.trim(),text=normaliseSpeech(original);if(handleCourseSpeech(original,text))return;const distanceInfo=parseDistance(text),base=distanceInfo?distanceInfo.value:getCurrentCentreDistance(),lie=parseLie(text),q=parseLieQuality(text),wind=parseWind(text),elevation=parseElevation(text),hazard=parseHazards(text),useful=Boolean(distanceInfo||lie!=="fairway"||elevation||hazard.water||hazard.bunker||hazard.trees||hazard.trouble||/\bwind\b|\bheadwind\b|\btailwind\b|\bcrosswind\b/.test(text));if(!useful){const m="Give me the distance, lie or trouble. Example: 155 rough, water left.";$("lastShot").textContent="Heard: "+original;setCaddieAnswers(m);speak(m);return}const playing=calculatePlayingDistance(base,lie,q,wind,elevation),club=chooseClubForShot(playing,lie,hazard),parts=[];setRecommendedClub(club);parts.push((distanceInfo?formatDistance(base)+", ":"")+describeLie(lie,q)+".");if(Math.abs(playing-base)>=2)parts.push("Playing "+formatDistance(playing)+".");parts.push(club+".");const ha=buildHazardAdvice(hazard),wa=buildWindAdvice(wind),lc=buildLieCue(lie,q);if(ha)parts.push(ha);if(wa)parts.push(wa);if(lc)parts.push(lc);if(elevation>0)parts.push("Uphill — take the number.");else if(elevation<0)parts.push("Downhill — control the carry.");if(/\bdraw\b/.test(text))parts.push("Set the draw start line.");if(/\bfade\b/.test(text))parts.push("Set the fade start line.");if(/\bknockdown\b|\bpunch\b|\blow shot\b/.test(text))parts.push("Three-quarter finish.");parts.push("Commit.");const advice=parts.join(" ").replace(/\s+/g," ").trim();$("lastShot").textContent="Heard: "+original;setCaddieAnswers(advice);speak(advice)}
function speak(t){if(!("speechSynthesis"in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang="en-AU";u.rate=.95;u.pitch=1;u.volume=1;speechSynthesis.speak(u)}
function updateCaddiePage(){if(!$("caddieHole"))return;const h=holes[currentHole],d=displayDistance(getCurrentCentreDistance()),n=getCaddieName();$("largeCaddieName").textContent=n;$("caddieHole").textContent=h.hole;$("caddieDistance").textContent=d.value+" "+d.unit;$("caddieClub").textContent=$("recommendedClub").textContent}
function renderBag(){$("bagRows").innerHTML="";Object.entries(bagMetres).forEach(([club,carry])=>{const d=displayDistance(carry),r=document.createElement("div");r.className="bag-row";r.innerHTML='<div class="bag-club">'+club+'</div><input class="bag-input" type="number" data-club="'+club+'" value="'+d.value+'"><div class="bag-unit">'+d.unit+"</div>";$("bagRows").appendChild(r)})}
function saveBag(){$$(".bag-input").forEach(i=>{let v=Number(i.value);if(unitMode==="imperial")v*=YARDS_TO_METRES;if(v>=0&&Number.isFinite(v))bagMetres[i.dataset.club]=Math.round(v)});localStorage.setItem("drcBagMetres",JSON.stringify(bagMetres));renderBag();recommendClub();alert("My Bag saved.")}
function updateCoursePage(){if(!$("courseHoleNumber"))return;const h=holes[currentHole],d=displayDistance(getCurrentCentreDistance());$("courseHoleNumber").textContent=h.hole;$("coursePar").textContent=h.par;$("courseDistance").textContent=d.value+" "+d.unit}
function toggleUnits(){unitMode=unitMode==="metric"?"imperial":"metric";localStorage.setItem("drcUnitMode",unitMode);renderHole();renderBag();updateMorePage()}
function updateMorePage(){if(!$("unitToggle"))return;$("unitToggle").textContent=unitMode==="metric"?"METRES":"YARDS";$("moreCaddieName").value=getCaddieName();updateGpsDisplay()}
function renderScorecard(){const body=$("scorecardBody");body.innerHTML="";let totalPar=0,totalScore=0,played=0;holes.forEach(h=>{totalPar+=h.par;const d=holeScores[h.hole],score=d&&d.score>0?d.score:0;if(score){totalScore+=score;played++}const r=document.createElement("tr");r.innerHTML="<td>"+h.hole+"</td><td>"+h.par+"</td><td>"+(score||"–")+"</td><td>"+(d?d.putts:"–")+"</td><td>"+(d&&d.gir?"✓":"–")+"</td><td>"+(d&&d.fairway?"✓":"–")+"</td><td>"+(d?d.penalty:"–")+"</td>";body.appendChild(r)});$("totalPar").textContent=totalPar;$("totalScore").textContent=totalScore||"–";$("toPar").textContent=played===18?(totalScore-totalPar===0?"E":totalScore-totalPar>0?"+"+(totalScore-totalPar):totalScore-totalPar):"–"}
function selectPracticeType(btn,type){practiceType=type;$$(".practice-type").forEach(b=>b.classList.remove("active"));btn.classList.add("active")}
function selectShape(btn,shape){practiceShape=shape;$$(".shape-btn").forEach(b=>b.classList.remove("active"));btn.classList.add("active")}
function practiceAdd(type){practiceCounts[type]++;renderPracticeCounts()}
function renderPracticeCounts(){$("practiceGood").textContent=practiceCounts.good;$("practiceLeft").textContent=practiceCounts.left;$("practiceRight").textContent=practiceCounts.right;$("practiceShort").textContent=practiceCounts.short;$("practiceLong").textContent=practiceCounts.long}
function renderPractice(){renderPracticeCounts()}
function resetPractice(){practiceCounts={good:0,left:0,right:0,short:0,long:0};$("practiceNote").value="";renderPracticeCounts()}
function savePractice(){const s=JSON.parse(localStorage.getItem("drcPracticeHistory")||"[]");s.unshift({date:new Date().toISOString(),type:practiceType,shape:practiceShape,counts:{...practiceCounts},note:$("practiceNote").value.trim()});localStorage.setItem("drcPracticeHistory",JSON.stringify(s));alert("Practice session saved.")}
function renderChecklist(cid,steps,state,toggle,pid,tid){const c=$(cid);c.innerHTML="";steps.forEach((step,i)=>{const r=document.createElement("div");r.className="check-row";r.innerHTML='<button class="check-button '+(state[i]?"done":"")+'" onclick="'+toggle+'('+i+')">'+(state[i]?"✓":"")+'</button><div><div class="check-title">'+step[0]+'</div><div class="check-small">'+step[1]+"</div></div>";c.appendChild(r)});const done=state.filter(Boolean).length;$(pid).style.width=done/steps.length*100+"%";$(tid).textContent=done+" of 8 complete"}
function renderWarmup(){renderChecklist("warmupRows",warmupSteps,warmupState,"toggleWarmup","warmupProgress","warmupProgressText")}
function toggleWarmup(i){warmupState[i]=!warmupState[i];localStorage.setItem("drcWarmupState",JSON.stringify(warmupState));renderWarmup()}
function resetWarmup(){warmupState=new Array(8).fill(false);localStorage.setItem("drcWarmupState",JSON.stringify(warmupState));renderWarmup()}
function renderRoutine(){renderChecklist("routineRows",routineSteps,routineState,"toggleRoutine","routineProgress","routineProgressText")}
function toggleRoutine(i){routineState[i]=!routineState[i];localStorage.setItem("drcRoutineState",JSON.stringify(routineState));renderRoutine()}
function resetRoutine(){routineState=new Array(8).fill(false);localStorage.setItem("drcRoutineState",JSON.stringify(routineState));renderRoutine()}
